### ISSUE TITLE
ECS SDK无法编译，clone下来的代码中有一些空文件

### ISSUE THREAD

**Issue by notsyncing** [aliyun/aliyun-openapi-net-sdk#1]
例如Transform/V20140526/下的
DescribeTagKeysResponseUnmarshaller.cs
AllocatePublicIpAddressResponseUnmarshaller.cs
等多个虽然有大小但内容均为二进制0的文件

clone的代码最后一个commit：f4335d05ba0272f60e08300257188977f3148484

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
