### ISSUE TITLE
支持 dotnet core

### ISSUE THREAD

**Issue by cuiliang** [aliyun/aliyun-openapi-net-sdk#11]
建议支持dotnet core从而可以跨平台使用。

**Comment by zhang1yun1** [comment]
附议，求支持dotnet core

**Comment by HADB** [comment]
+1

**Comment by HADB** [comment]
有兴趣的可以看我这个fork https://github.com/HADB/aliyun-openapi-net-sdk
做了一些努力，但是仍有两个问题没能解决，主要是公用的aliyun-net-sdk-core底层的一些问题，有能力的可以帮忙看下。
1. .net core下HttpWebRequest发生了很大的变化，感觉底层的GetResponse方法得用HttpClient重写，或者不知道有没有别的解决办法
2. .net core下System.Reflection也有些方法不支持了，MethodBase.GetCurrentMethod()和Assembly.GetExecutingAssembly()均没有找到替代方法

**Comment by VAllens** [comment]
已经解决，更新到支持.net core 1.0 以上版本，并且已pull request到[Added support for .NET Core with netstandard 1.0](https://github.com/aliyun/aliyun-openapi-net-sdk/pull/14)
我改动后的源码地址[aliyun-openapi-sdk-net-core](https://github.com/VAllens/aliyun-openapi-sdk-net-core)
欢迎提建议和探讨技术，谢谢。

**Comment by tldzyx** [comment]
@VAllens 看了下你打的包都是针对.net core的, 可否改成.net standard版本的呢?
