### ISSUE TITLE
MNS的为啥不在这里头？而且也没有.Net Core 的。 好烦躁啊。 

### ISSUE THREAD

**Issue by maikebing** [aliyun/aliyun-openapi-net-sdk#15]
MNS的为啥不在这里头？而且也没有.Net Core 的。 好烦躁啊。

**Comment by conan425** [comment]
您可以先参考我们的Common Api，按照文档组织参数就可以了，谢谢！
https://help.aliyun.com/document_detail/61473.html?spm=5176.doc53095.6.561.0NxRDa
