### ISSUE TITLE
aliyun-net-sdk-scdn SDK.InvalidRegionId : Can not find endpoint to access

### ISSUE THREAD

**Issue by sdtamk** [aliyun/aliyun-openapi-net-sdk#166]
使用官方sdk刷新scdn，报错
IClientProfile profile = DefaultProfile.GetProfile("https:scdn.aliyuncs.com", AppCode.AliyunConfig.ACCESS_KEY_ID, AppCode.AliyunConfig.ACCESS_KEY_SECRET);
var rid=profile.GetRegionId();
DefaultAcsClient client = new DefaultAcsClient(profile);
try
{
    Aliyun.Acs.scdn.Model.V20171115.RefreshScdnObjectCachesRequest request = new Aliyun.Acs.scdn.Model.V20171115.RefreshScdnObjectCachesRequest();
    request.ObjectType = ddlScdnType.SelectedValue;
    request.ObjectPath = path;
    var respone = client.GetAcsResponse(request);
}
catch (Exception ex)
{
    logger.Error(ex, "发生异常");
    throw;
}
错误信息：SDK.InvalidRegionId : Can not find endpoint to access.
在aliyun-net-sdk-core的配置文件endpoints.xml中并未找到scdn的配置项

**Comment by doublnt** [comment]
@sdtamk 您好，我在本地复现了一下您的问题，应该是您的RegionId 写错了，具体的RegionId你可以参考下面这个地址。
[地域和可用区](https://help.aliyun.com/document_detail/40654.html?spm=5176.10695662.1996646101.1.428f33dcqFeXaM) 。如果还是有问题，麻烦您继续在issue下留言。

**Comment by AxiosCros** [comment]
https:scdn.aliyuncs.com 这个RegionID是无效的，试试用cn-hangzhou或者其它的RegionID

**Comment by AxiosCros** [comment]
@sdtamk 
我先关闭这个issue了，如果还有问题，您可以重新开启issue。
