### ISSUE TITLE
where is package `aliyun-net-sdk-afs`?

### ISSUE THREAD

**Issue by WeihanLi** [aliyun/aliyun-openapi-net-sdk#169]
can not find the package `aliyun-net-sdk-afs`  on nuget.

**Comment by doublnt** [comment]
您好，您所需要的 `aliyun-net-sdk-afs` 已发布至nuget，需要nuget verify 之后才会正式公布
，您可以在 https://www.nuget.org/packages?q=aliyun 里找到所需的包，然后使用
`dotnet add package Aliyun.Acs.Afs --version 1.0.0` 命令进行安装。

**Comment by WeihanLi** [comment]
```
unable to find package Aliyun.Acs.Afs
```

**Comment by doublnt** [comment]
You can download this package in following site: https://www.nuget.org/packages/aliyun-net-sdk-afs/ ,
and using `dotnet add package aliyun-net-sdk-afs --version 1.0.0` in your target project folder;

**Comment by WeihanLi** [comment]
Ok, thanks for your effort
