### ISSUE TITLE
Could not install package 'aliyun-net-sdk-ecs 4.16.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content f iles that are compatible with that framework. For more information, contact the package author.

### ISSUE THREAD

**Issue by lmc309** [aliyun/aliyun-openapi-net-sdk#172]
![image](https://user-images.githubusercontent.com/2479230/54062283-16d66400-4240-11e9-8350-ab38d9ebe35c.png)

![image](https://user-images.githubusercontent.com/2479230/54062301-28b80700-4240-11e9-972e-232a1d0b0d57.png)

* **Dotnet Core Version**:
* **Platform**:
* **Product**:
* **Product Version**:
* **API**:

**Comment by lmc309** [comment]
AS what you said in Prerequisites
The Alibaba Cloud C# SDK is requires .NET Framework 4.0 or later.

**Comment by doublnt** [comment]
@lmc309 Sorry to hear about that. If you want to use `aliyun-net-sdk-ecs 4.16.1` product, you should install [aliyun-net-sdk-core 1.2.0](https://www.nuget.org/packages/aliyun-net-sdk-core/) either. And the aliyun-net-sdk-core 1.2.0 has the dependency `.NETStandard 2.0` which is not support .net framework now in 1.2.0 version. We will support the .net framework in next version 1.2.1 which will release next week. Sometimes, the document does not up to date.

**Comment by doublnt** [comment]
@lmc309  I found you are using wrong nuget package version, you are using `aliyun-net-sdk-core-1.1.0` and `aliyun-net-sdk-ecs 4.16.1` , as you can see the [ecs product](https://www.nuget.org/packages/aliyun-net-sdk-ecs/4.16.1). In the Dependencies Section, the `aliyun-net-sdk-core` version should be greater than 1.1.12.

You can use the following command in your project,

```shell
dotnet add package aliyun-net-sdk-core --version 1.1.12
dotnet add package aliyun-net-sdk-ecs --version 4.16.1
```
It run success in my local test environment.
