### ISSUE TITLE
vod 中的 GetVideoPlayInfoRequest  参数 ClientTS 是什么

### ISSUE THREAD

**Issue by jzpenghaitao** [aliyun/aliyun-openapi-net-sdk#18]
vod 中的 GetVideoPlayInfoRequest  参数 ClientTS表示什么？

**Comment by conan425** [comment]
@jzpenghaitao 您好，请您参考阿里云对应产品的官方Api文档，如果没有查到您想要的，可以通过客服或者提交工单的形式告诉我们，我们会有专门的同学去解决，谢谢！
