### ISSUE TITLE
建议补充下Demo.

### ISSUE THREAD

**Issue by RocherKong** [aliyun/aliyun-openapi-net-sdk#202]
* **Dotnet Core 版本**：2.0
* **平台**：
* **产品名称**：
* **产品版本**：
* **API**：

https://help.aliyun.com/document_detail/101874.html?spm=a2c4g.11186623.4.1.6a0b5f30GHyhpD 唯独.Net SDK没有Demo.建议补全。

**Comment by doublnt** [comment]
您好，感谢您的建议，其实已经有demo ，只是官网上还没同步，后续我们会沟通加上链接，您可以在该地址查看所需服务的.NET  Demo https://api.aliyun.com/?spm=a2c4g.11186623.2.14.15ea50a4o50Yab#/?product=Dysmsapi&api=QuerySendDetails&params={}&tab=DEMO&lang=CSHARP

**Comment by RocherKong** [comment]
好的，谢谢。
