### ISSUE TITLE
[Suggestion] Add appropriate code analyzers and make some significant rules build blocker 

### ISSUE THREAD

**Issue by hanabi1224** [aliyun/aliyun-openapi-net-sdk#207]
It will be great to add appropriate code analyzers and make some significant rules build blocker to improve code quality.  Please let me know your concerns

**Comment by doublnt** [comment]
I am developing with `vs code`. I didn't use the analyzer before although there are some tools like microsoft analyzer.  You can push a pull request about the low code quality in our code.

**Comment by hanabi1224** [comment]
@doublnt  Sure, i have created https://github.com/aliyun/aliyun-openapi-net-sdk/pull/208 so that you can selectively block on CA rules that are significant. (In the PR I only fixed a small one for demonstrating the idea tho)

**Comment by doublnt** [comment]
@hanabi1224 Thanks for your advice, I will test in my local dev environment.

**Comment by doublnt** [comment]
@hanabi1224 Thanks for your advice, I have downloaded and import the package in our project. But it seems that the tool is similar to `Resharper` or `Visual Assist Tool` in Visual Studio. In the meanwhile, I can refactor my code when coding or debugging . It is no doubt that there are many shortcoming and inappropriate in our code. We are looking forward that you can improve the code quality with us together.

**Comment by doublnt** [comment]
@hanabi1224  I will update the code style and format standard for contributor in this week. Thanks for your advice.
