### ISSUE TITLE
使用STS授权信息

### ISSUE THREAD

**Issue by LilacXiao** [aliyun/aliyun-openapi-net-sdk#24]
https://help.aliyun.com/document_detail/57114.html 在这个文档示例里面，JAVA版本使用STS授权去获取上传凭证时，有request.setSecurityToken(token); 方法，但是.NET版本的没有。那么.NET获取上传凭证 怎么去使用STS授权呢？

**Comment by conan425** [comment]
@LilacXiao 您好，现在.net SDK已经支持Sts授权了，请参考：https://help.aliyun.com/document_detail/66511.html?spm=a2c4g.11186623.6.608.jNcYZP
