### ISSUE TITLE
请添加dyvmsapi的endpoint

### ISSUE THREAD

**Issue by moonheart** [aliyun/aliyun-openapi-net-sdk#240]
* **Dotnet Core Version**: .Net Framework 4.7.2
* **Platform**: Windows
* **Product**: dyvmsapi
* **Product Version**: 3.0.0
* **API**: aliyun-net-sdk-dyvmsapi

请在 [endpoints.xml](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/master/aliyun-net-sdk-core/Regions/endpoints.xml) 添加dyvmsapi的endpoint. 

目前如果使用 [aliyun-net-sdk-dyvmsapi](https://github.com/aliyun/aliyun-openapi-net-sdk/tree/master/aliyun-net-sdk-dyvmsapi) 会抛出 `Can not find endpoint to access.` 的异常

https://github.com/aliyun/aliyun-openapi-net-sdk/blob/5d0ca86c70fcfc9ddd76b728aa408601e3d12fe1/aliyun-net-sdk-core/DefaultAcsClient.cs#L269-L272

**Comment by AxiosCros** [comment]
dyvmsapi 的全局域名是 dyvmsapi.aliyuncs.com ，因dyvmsapi暂时没有登记在location服务上，所以目前请使用 AddEndpoint 方法手动添加。
使用示例:
```
DefaultProfile.AddEndpoint("cn-hangzhou", "cn-hangzhou", "Dyvmsapi", "dyvmsapi.aliyuncs.com");
```

**Comment by moonheart** [comment]
好的，非常感谢您的解答。

**Comment by haihongS** [comment]
我这边解决方法如下：
```
req = SingleCallByTtsRequest()
req.set_endpoint('dyvmsapi.aliyuncs.com')
```
