### ISSUE TITLE
aliyun-net-sdk-green 为啥没有demo 官方文档上也找不到

### ISSUE THREAD

**Issue by charliejinc** [aliyun/aliyun-openapi-net-sdk#251]
aliyun-net-sdk-green 文本反垃圾 这种为啥没有官方文档，我这边传中文文本 到平台上 乱码，好烦躁，不知道怎么办

**Comment by doublnt** [comment]
您好 稍等 我帮您找一下。

**Comment by doublnt** [comment]
Demo ： https://api.aliyun.com/#/?product=Green&api=TextScan&params={}&tab=DEMO&lang=CSHARP
API： https://help.aliyun.com/document_detail/70409.html?spm=a2c4g.11186623.6.568.722920b9ajP0X5

**Comment by charliejinc** [comment]
> Demo ： [https://api.aliyun.com/#/?product=Green&api=TextScan&params={}&tab=DEMO&lang=CSHARP](https://api.aliyun.com/#/?product=Green&api=TextScan&params=%7B%7D&tab=DEMO&lang=CSHARP)
> API： https://help.aliyun.com/document_detail/70409.html?spm=a2c4g.11186623.6.568.722920b9ajP0X5

好的谢谢 已经解决
