### ISSUE TITLE
aliyun-net-sdk-core更新到1.3.2后报找不到1.2.3

### ISSUE THREAD

**Issue by xxvolvo** [aliyun/aliyun-openapi-net-sdk#253]
aliyun-net-sdk-core更新到1.3.2后报 {"Could not load file or assembly 'aliyun-net-sdk-core, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。":"aliyun-net-sdk-core, Version=1.2.3.0, Culture=neutral, PublicKeyToken=null"}

使用了aliyun-net-sdk-mts和不在此项目中的Aliyun.OSS.SDK.NetCore 降级到1.2.9恢复正常

**Comment by doublnt** [comment]
@xxvolvo 您好，稍等。我排查一下。

**Comment by doublnt** [comment]
@xxvolvo  您好，麻烦您升级一下 MTS 包的版本至 2.6.2 可以解决此问题，
`<PackageReference Include="aliyun-net-sdk-mts" Version="2.6.2" />` 
Core 包不用降级，Core包可以使用 1.3.2.0 版本
`<PackageReference Include="aliyun-net-sdk-core" Version="1.3.2" />` 
与 `Aliyun.OSS.SDK.NetCore` 这个包没有关系。
