### ISSUE TITLE
vs2017以下版本 无法编译 主要里面代码用c#7.0新特性  vs2013 .net framework 4.5 和.net framework 4 都不行

### ISSUE THREAD

**Issue by ylean** [aliyun/aliyun-openapi-net-sdk#255]
错误	13	类、结构或接口成员声明中的标记“(”无效	E:\公司\yl\DavToMp4\aliyun-openapi-net-sdk-master\aliyun-net-sdk-core\AcsRequest.cs	58	105	aliyun-net-sdk-core.net45

**Comment by doublnt** [comment]
@ylean 您好，麻烦您提供相关的编译错误信息。

**Comment by ylean** [comment]
------------------ 原始邮件 ------------------
发件人: "doublnt"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 上午10:42
收件人: "aliyun/aliyun-openapi-net-sdk"<aliyun-openapi-net-sdk@noreply.github.com>;
抄送: "毛俊贤"<258258001@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [aliyun/aliyun-openapi-net-sdk] vs2017 无法编译 主要里面代码用c#7.0新特性 (#255)




@ylean 您好，麻烦您提供相关的编译错误信息。

**Comment by doublnt** [comment]
@ylean 请问您使用的 Visual Studio 版本，和 .net framework 框架版本?

**Comment by doublnt** [comment]
@ylean 您好，代码中用到了 C# 6.0 `'auto property initializer' ` 特性，导致无法在 C# 6.0 以下的版本中使用。很抱歉给您带来了不便，我们会尽快向低版本的 C# 版本兼容。

**Comment by tom-branden** [comment]
现在SDK最低兼容的版本是VS2017？

**Comment by doublnt** [comment]
@tom-branden 
- 目前 `aliyun-net-sdk-core.netstandard20.sln` 使用的是 `.net standard 2.0` ，C# 版本需要 >= 6.0 建议推荐在 `Visual Studio 2017` 及以上 IDE 进行开发。
- `aliyun-net-sdk-core.net45.sln` 使用的是 `.net 4.5` 框架, 可以在 `Visual Studio 2015` IDE 上进行开发。

**Comment by tom-branden** [comment]
![image](https://user-images.githubusercontent.com/49580411/58394689-1ac39680-8077-11e9-8f4d-4a9cc11c14af.png)
VS2015

**Comment by doublnt** [comment]
@tom-branden nas 的 Nuget 包，依赖的 Core 为 1.1.12 版本（其项目目标框架为 net standard2.0），需要重新发布该 Nuget，使其适配 net45 版本。

**Comment by doublnt** [comment]
@ylean 目前支持 C# version >=4.0  且 .NET Framework 版本 >= 4.5

**Comment by doublnt** [comment]
@tom-branden [NAS Version 3.2.1](https://www.nuget.org/packages/aliyun-net-sdk-nas/3.2.1)， 本地测试 net452 可以正常使用。
