### ISSUE TITLE
sdk安装

### ISSUE THREAD

**Issue by luojingshun125** [aliyun/aliyun-openapi-net-sdk#264]
安装.net sdk 报错呀

**Comment by doublnt** [comment]
@luojingshun125 您好，请提供详细的相关错误信息以及您使用的框架和SDK版本

**Comment by JacksonTian** [comment]
@doublnt 检查下 github issue template 为什么没有生效。

**Comment by doublnt** [comment]
> @doublnt 检查下 github issue template 为什么没有生效。

OK

**Comment by luojingshun125** [comment]
用的是ABP框架   版本就是从你们https://github.com/aliyun/aliyun-openapi-net-sdk/tree/master/aliyun-net-sdk-core?spm=a2c4g.11186623.2.13.3b204923b0yyxa 这里拿的
![Uploading image.png…]()
  这是报错

**Comment by doublnt** [comment]
@luojingshun125 您好，无法加载您上传的图片，麻烦重新上传一下。

**Comment by luojingshun125** [comment]
![image](https://user-images.githubusercontent.com/51221320/58686233-d60a6900-83b0-11e9-916a-a8662018cbec.png)

**Comment by doublnt** [comment]
@luojingshun125, 您好，这个错误是 Nuget 包没有安装的原因，麻烦您在 `Pacakge Manager Console` 中执行 `Update-Package -Reinstall` 即可解决您的问题。

**Comment by luojingshun125** [comment]
![image](https://user-images.githubusercontent.com/51221320/58686820-7a40df80-83b2-11e9-9385-f5db78ea1735.png)
没用

**Comment by doublnt** [comment]
您图片中的错误是还原 dapper 包时报的错误，请问您项目的目标框架是 .net framework 4.6.1 ?

**Comment by luojingshun125** [comment]
4.5.2

**Comment by doublnt** [comment]
您遇到的这个问题主要是 nuget 包还原失败导致找不到相应的程序集的错误，您可以解决的办法第一个是通过运行`Update-Package -Reinstall` 这个命令，第二是通过在 Nuget Package Manager 中手动安装 Serilog 2.5.0 版本的包。

**Comment by luojingshun125** [comment]
![image](https://user-images.githubusercontent.com/51221320/58687670-e290c080-83b4-11e9-94f9-73c91eb59392.png)
这个包已经安装过了的

**Comment by luojingshun125** [comment]
![image](https://user-images.githubusercontent.com/51221320/58688036-ebce5d00-83b5-11e9-8064-2172bea3a502.png)

这个环境是必须要搭么

**Comment by doublnt** [comment]
> ![image](https://user-images.githubusercontent.com/51221320/58687670-e290c080-83b4-11e9-94f9-73c91eb59392.png)
> 这个包已经安装过了的

如果已安装该包，还是找不到引用的话，在项目引用中添加 该包的 引用

**Comment by doublnt** [comment]
> ![image](https://user-images.githubusercontent.com/51221320/58688036-ebce5d00-83b5-11e9-8064-2172bea3a502.png)
> 
> 这个环境是必须要搭么

你这个文档是阿里云项目的文档说明吗？

**Comment by luojingshun125** [comment]
是的

**Comment by luojingshun125** [comment]
![image](https://user-images.githubusercontent.com/51221320/58688776-f8ec4b80-83b7-11e9-86c0-700e3910089e.png)
![image](https://user-images.githubusercontent.com/51221320/58688796-03a6e080-83b8-11e9-8e29-254ee6adb8c9.png)
引用的也引用了  这咋还报错  纳闷了

**Comment by doublnt** [comment]
@luojingshun125  您好，很抱歉给您带来了不便，目前在 `aliyun-net-sdk-vod.vs2017.csproj` 同时对 .net standard 2.0 和 .net framework 45 进行了兼容，麻烦您打开 `aliyun-net-sdk-vod.vs2017.csproj` 进行编译哦

**Comment by luojingshun125** [comment]
![image](https://user-images.githubusercontent.com/51221320/58689381-73699b00-83b9-11e9-904d-07cbc84ffbb3.png)
我是vs2015耶

**Comment by doublnt** [comment]
您好，稍等。我发布一个新版本的 Vod 的nuget 包，兼容 .net 45 框架的，到时您直接安装新版本的 Nuget 包就行了，不需要本地编译，如果还有问题的话，麻烦 加一下钉钉群 11771185，描述一下您的问题。
