### ISSUE TITLE
aliyun-net-sdk-core 调号码认证API 报“Specified parameter Version is not valid.”  但是版本号按文档填写

### ISSUE THREAD

**Issue by yanglin1994** [aliyun/aliyun-openapi-net-sdk#271]
* **Dotnet Core 版本**：
* **平台**：.net core 2.1
* **产品名称**：号码认证服务
* **产品版本**：2017-05-25
* **API**：GetMobile

![微信截图_20190611102928](https://user-images.githubusercontent.com/33014379/59239381-d964e680-8c33-11e9-9271-525685b42650.png)

**Comment by doublnt** [comment]
@yanglin1994 您好，请稍等。正在为您排查该问题。

**Comment by yanglin1994** [comment]
我使用go的sdk 填写一样的信息 能返回正确的信息

**Comment by doublnt** [comment]
@yanglin1994 麻烦您参考一下这个 API Explorer 中 .NET 的代码试试，https://api.aliyun.com/#/?product=Dypnsapi&api=GetMobile&params={}&tab=DEMO&lang=CSHARP

**Comment by yanglin1994** [comment]
我就是使用的API Explorer 中 .NET 的代码

**Comment by yanglin1994** [comment]
唯一与API Explorer 中 .NET 的代码不同的是我将Action换成UriPattern了

**Comment by doublnt** [comment]
@yanglin1994  您换成这样试试
```c#
CommonRequest request = new CommonRequest
            {
                Method = MethodType.POST,
                Domain = "dypnsapi.aliyuncs.com",
                Version = "2017-05-25",
                Action = "GetMobile",
                Protocol = ProtocolType.HTTPS
            };
```

**Comment by yanglin1994** [comment]
可以获取到了  谢谢！  但是我是看了.net sdk的使用文档 RESTful风格调用的  为什么会出现我这个问题呢？

**Comment by doublnt** [comment]
@yanglin1994 有些参数是某些接口强制要求的，还是建议您参考Demo上面的代码示例哦。
