### ISSUE TITLE
阿里云物联网平台接口问题

### ISSUE THREAD

**Issue by dafeifei0218** [aliyun/aliyun-openapi-net-sdk#288]
1、没有查询全部产品的功能，只能分页查询。
请看：https://help.aliyun.com/document_detail/69271.html?spm=a2c4g.11186623.6.691.670a295cWEv95e
2、没有查询全部设备的功能，只能按照产品Key分页查询，请开放此功能。
没有按照备注查询设备的功能，请接口多加几个参数。  
请看：https://help.aliyun.com/document_detail/69905.html?spm=a2c4g.11186623.6.702.404a55f54M7sxW

**Comment by dafeifei0218** [comment]
关于第2点，请开放按照全部产品查询设备的功能。

**Comment by doublnt** [comment]
@dafeifei0218 您好，关于 iot 产品相关功能的问题，麻烦您请提相关工单进行咨询。

**Comment by dafeifei0218** [comment]
提工单了...
![image](https://user-images.githubusercontent.com/10148878/60695247-a56ba100-9f13-11e9-81fa-b70ec9a58916.png)

**Comment by doublnt** [comment]
@dafeifei0218 亲，产品相关API 和功能问题，如有相关需求，请提工单给相关产品进行相应支持。谢谢。
