### ISSUE TITLE
DefaultAcsClient's DoAction<T> overload methods have BUG

### ISSUE THREAD

**Issue by VAllens** [aliyun/aliyun-openapi-net-sdk#29]
### Error Code
```csharp
FormatType? requestFormatType = request.AcceptFormat;
if (null != requestFormatType)
{
	format = requestFormatType;
}
```

### Right Code
```csharp
if (null == format)
{
	format = request.AcceptFormat;
}
```

I see that this method has Nullable<T> type parameter `format`.
I thought you were going to judge if the parameter `format` was empty, otherwise the code **`if (null != requestFormatType)`** would be meaningless. **Because it's always `true`**.

**Comment by conan425** [comment]
We will consider your suggestion，Thank you very much!
