### ISSUE TITLE
Does DefaultAcsClient thead safe (concurrent call) like System.Net.Http.HttpClient ?

### ISSUE THREAD

**Issue by GreatFireWall** [aliyun/aliyun-openapi-net-sdk#293]
If not, please add this feature. :)

**Comment by doublnt** [comment]
DefaultAcsClient is not like HttpClient, the network library we used in sdk is  HttpWebRequest. GetAcsResponse is not thread safe.

**Comment by GreatFireWall** [comment]
Got it. Thanks.
