### ISSUE TITLE
泰语下中URL地址的拼接问题

### ISSUE THREAD

**Issue by xueandfeng** [aliyun/aliyun-openapi-net-sdk#296]
* **Dotnet Core 版本**：
* **平台**：centos 7/docker
* **产品名称**：dysmsapi
* **产品版本**：2017-05-25
* **API**：
因为最近我的项目是多语言功能（中,英,泰）
使用的是ASP.NET Core 全球化和本地化(https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/localization?view=aspnetcore-2.2)
然后发现部署在docker下的时候。中文和英文请求NewLife.Redis是连接正常的没有问题.
当是泰语的时候发现
https://github.com/aliyun/aliyun-openapi-net-sdk/blob/master/aliyun-net-sdk-core/RpcAcsRequest.cs#L166
![image](https://user-images.githubusercontent.com/20178645/62450713-68f3c500-b79f-11e9-93d5-7a90829d6c11.png)

**Comment by xueandfeng** [comment]
https://github.com/aliyun/aliyun-openapi-net-sdk/pull/297
提交了PR

**Comment by AxiosCros** [comment]
@xueandfeng 
感谢～请在 PR 里签一下 CLA。

**Comment by AxiosCros** [comment]
@xueandfeng 

代码已合入。
