### ISSUE TITLE
.NET SDK DescribeAvailableResource接口返回实体有误

### ISSUE THREAD

**Issue by SaikiCode** [aliyun/aliyun-openapi-net-sdk#299]
* **Dotnet Core 版本**：2.2
* **平台**：Windows
* **产品名称**：ECS
* **产品版本**：V20140526
* **API**：DescribeAvailableResource

接口返回JSON属性值为 Value 实体属性为 _Value 导致直接引用实体无法获取到值

图一为API Explorer调用结果
![1](https://user-images.githubusercontent.com/17064597/63068255-0b047180-bf45-11e9-9082-cccb7770d60d.png)
图二为直接引用SDK实体对象结果
![2](https://user-images.githubusercontent.com/17064597/63068256-0b047180-bf45-11e9-9757-dd5bc0775803.png)
图三为将SDK返回的HttpRespsonce的Content转化为字符串的结果
![3](https://user-images.githubusercontent.com/17064597/63068258-0b9d0800-bf45-11e9-98a1-0f9c55669cc0.png)

建议:
把SDK中类DescribeAvailableResourceResponse.DescribeAvailableResource_AvailableZone.DescribeAvailableResource_AvailableResource.DescribeAvailableResource_SupportedResource的  _Value  属性  修正为  Value

**Comment by AxiosCros** [comment]
@SaikiCode 

问题已解决，请使用 [aliyun-net-sdk-ecs](https://www.nuget.org/packages/aliyun-net-sdk-ecs) 4.17.5 版本
