### ISSUE TITLE
为什么少很多api啊，alidns的就没有

### ISSUE THREAD

**Issue by lersh** [aliyun/aliyun-openapi-net-sdk#3]
相比java的少了很多api啊，alidns的api更新在哪里呢？
我从[帮助页](https://help.aliyun.com/document_detail/29821.html?spm=5176.doc29745.6.210.5klXPI)下载的C#的sdk，在获取domainrecordinfo时，value一直是空，这个bug能修正吗

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
