### ISSUE TITLE
.net 4.6.1 从nuget上安装 cdn sdk, 使用时会报错  未能加载文件或程序集“System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

### ISSUE THREAD

**Issue by aaronzoe** [aliyun/aliyun-openapi-net-sdk#31]
未能加载文件或程序集“System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

**Comment by simhgd** [comment]
nuget上的包不是 fx的 是core的

**Comment by lhdboy** [comment]
nuget上的是.net core的，fw用不了；解决办法就是下载这个项目的zip然后找到你要的包在vs你的解决方案上添加你要的项目。

**Comment by conan425** [comment]
@aaronzoe 您的问题我们已经记录下来了，后续我们会考虑如何优化下这个问题，谢谢！
