### ISSUE TITLE
NullReferenceException when initializing InvokeDataAPIServiceRequest Params.

### ISSUE THREAD

**Issue by lss4** [aliyun/aliyun-openapi-net-sdk#319]
* **Dotnet Core Version**: 3.0.100-preview6-012264 (Actually targeting .NET Core 2.2)
* **Platform**: Windows 10 x64
* **Product**: aliyun-net-sdk-iot
* **Product Version**: 7.0.0 (from NuGet)
* **API**: InvokeDataAPIServiceRequest

I cannot initialize Params with a `List<InvokeDataAPIServiceRequest.Param>` that already has contents in it. Doing so throws NullReferenceException.

However, if I initialize Params with an empty list then add parameters later, it'll work without problems.

Examples (param1 and param2 are InvokeDataAPIServiceRequest.Param instances):

1. Non-working example:
```
List<InvokeDataAPIServiceRequest.Param> paramList = new List<InvokeDataAPIServiceRequest.Param>
{
	param1, param2
};

InvokeDataAPIServiceRequest req = new InvokeDataAPIServiceRequest
{
	ApiSrn = "MyAPISrn",
	Method = MethodType.GET,
	Params = paramList // throws NullReferenceException
};
```

2. Working example:
```
InvokeDataAPIServiceRequest req = new InvokeDataAPIServiceRequest
{
	ApiSrn = "MyAPISrn",
	Method = MethodType.GET,
	Params = new List<InvokeDataAPIServiceRequest.Param>() // This will not throw.
};

req.Params.Add(param1);
req.Params.Add(param2);
```

EDIT: The behavior is not correct... no matter how I pass the values it always behaves as if no parameters were given (the parameters were optional to begin with).

**Comment by lss4** [comment]
I have found the reason. It's [here](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/b7daa5042f8b4c46db2b8998cc795e40ac5655d1/aliyun-net-sdk-iot/Iot/Model/V20180120/InvokeDataAPIServiceRequest.cs#L72).

The Params' setter tried to access ListParamValues, which is null by default, as I was passing only a single value per parameter, I didn't initialize ListParamValues at this point, so NullReferenceException was thrown.

The correct solution is to follow the non-working example above, but make sure all four properties in 
`InvokeDataAPIServiceRequest.Param` are not null.

**Comment by AxiosCros** [comment]
Thank you for your feedback!
I will modify the SDK generator to make the param default value is empty, not null.

[code position](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/b7daa5042f8b4c46db2b8998cc795e40ac5655d1/aliyun-net-sdk-iot/Iot/Model/V20180120/InvokeDataAPIServiceRequest.cs#L44)

```
private List<Param> params_;
````
turn to 
```
private List<Param> params_ = new List<Param>(){};
```

This change will effect in the next release.
@lss4

**Comment by AxiosCros** [comment]
@lss4 

It is effect in [here](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/master/aliyun-net-sdk-iot/Iot/Model/V20180120/InvokeDataAPIServiceRequest.cs#L44).

please use  `aliyun-net-sdk-iot` package version [`7.0.1`](https://www.nuget.org/packages/aliyun-net-sdk-iot/7.0.1)

If the version is not Listed, wait a moment for Nuget Validating.

**Comment by lss4** [comment]
I just tested the 7.0.1 version with my current code and I have confirmed the problem has been fixed.

Thanks. Closing issue. :-)
