### ISSUE TITLE
aliyun-net-sdk-dybaseapi 的nuget包在哪里

### ISSUE THREAD

**Issue by mkc-xuliangjie** [aliyun/aliyun-openapi-net-sdk#330]
aliyun-net-sdk-dybaseapi 的nuget包在哪里？

**Comment by AxiosCros** [comment]
因 `[aliyun-net-sdk-dybaseapi](https://www.nuget.org/packages/aliyun-net-sdk-dybaseapi/)` 包名称被占用，所以官方自动生成的 SDK 没有成功发布到 nuget 平台上。

建议先使用源码编译的方式引用。
后续我们会考虑使用其它名称上传到 nuget 平台，或者联系 `aliyun-net-sdk-dybaseapi` 包所有者，更改这个包的所有权。
