### ISSUE TITLE
aliyun-net-sdk-core 中的Aliyun.Acs.Core.Logging;在哪？

### ISSUE THREAD

**Issue by wudao1234** [aliyun/aliyun-openapi-net-sdk#332]
请问aliyun-net-sdk-core中Aliyun.Acs.Core.Utils.CommonLog 用到了Aliyun.Acs.Core.Logging;但是我没找到他

**Comment by AxiosCros** [comment]
因为引用了 [LogLib.Common](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/88ba7cc1f7fd258bcba34af6b62dabf58b06b416/aliyun-net-sdk-core/aliyun-net-sdk-core.vs2017.csproj#L45)

[YourRootNamespace.Logging](https://github.com/doublnt/LibLog/blob/f0418dd984a279e9f176bc6282f95d2d5ac235b5/src/LibLog/LogProvider.cs#L42)

映射为了 `Aliyun.Acs.Core.Logging`

**Comment by AxiosCros** [comment]
@wudao1234 请问还有问题吗？没有的话，这个 issue 我先关了，如果还有问题再 reopen
