### ISSUE TITLE
Newtonsoft.Json dependency should not defined as <= 12.0.2

### ISSUE THREAD

**Issue by sdcb** [aliyun/aliyun-openapi-net-sdk#337]
Create a .NET Core 3.0 console application, find and install `aliyun-net-sdk-alidns` using Visual Studio 2019 `16.3.9`, the following warning will be prompt:
```
1>ConsoleApp4.csproj : warning NU1602: aliyun-net-sdk-alidns 2.0.11 未提供依赖项 Newtonsoft.Json (<= 12.0.2) 的包含下限。已解决 Newtonsoft.Json 3.5.8 的近似最佳匹配。
1>ConsoleApp4.csproj : warning NU1701: 已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8”而不是项目目标框架“.NETCoreApp,Version=v2.2”还原包“Newtonsoft.Json 3.5.8”。此包可能与项目不完全兼容。
1>    2 个警告
1>    0 个错误
```

This caused Visual Studio picking up the wrong version(3.5.8), which does not support .NET Core.

**Comment by Dolphinsimon** [comment]
Should be >=12.0.2

**Comment by liaoyustudent** [comment]
1. Please install aliyun-net-sdk-alidns 2.0.12  ,it can supported Newtonsoft.Json > 12.0.2
2. Please install aliyun-net-sdk-push 3.13.1  ,it can supported Newtonsoft.Json > 12.0.2
3. SDK  does not support .NET Core 3.0(standard 2.1). it will coming soon.

**Comment by Dolphinsimon** [comment]
> 1. Please install aliyun-net-sdk-alidns 2.0.12  ,it can supported Newtonsoft.Json > 12.0.2
> 2. Please install aliyun-net-sdk-push 3.13.1  ,it can supported Newtonsoft.Json > 12.0.2
> 3. SDK  does not support .NET Core 3.0(standard 2.1). it will coming soon.

Thanks for the newly published packages.  The current  packages work peroperly in .netcore3.0/3.1 projects.
