### ISSUE TITLE
aliyun-net-sdk-core 1.1.9更新提示警告

### ISSUE THREAD

**Issue by alfadb** [aliyun/aliyun-openapi-net-sdk#34]
Package 'aliyun-net-sdk-core 1.1.9' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

Package 'aliyun-net-sdk-core 1.1.9' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by conan425** [comment]
@alfadb 您本地使用的是.net Core框架？

**Comment by alfadb** [comment]
是的 .net core 2.0

**Comment by conan425** [comment]
@alfadb 我们目前.net SDK还不支持.net core，年后我们会尽快排期支持，谢谢您提的问题！

**Comment by alfadb** [comment]
好的，希望尽快安排，我们现在已经在生产环境使用了，之前我们用的应该是simhgd fork你们官方库做的.net core适配，但是他现在已经停止更新了

**Comment by conan425** [comment]
@alfadb 收到，我们尽快安排
