### ISSUE TITLE
为什么没有 Aliyun.Acs.Core.Logging

### ISSUE THREAD

**Issue by geebos** [aliyun/aliyun-openapi-net-sdk#342]
Aliyun.Acs.Core.Utils.CommonLog里使用了 Aliyun.Acs.Core.Logging但是没有相关的类。

**Comment by liaoyustudent** [comment]
你好，Aliyun.Acs.Core.Logging相关的类在LogLib.Common的引用里

**Comment by HappyBar** [comment]
> 你好，Aliyun.Acs.Core.Logging相关的类在LogLib.Common的引用里

请问“LogLib.Common”，在哪里可找到或下载？
