### ISSUE TITLE
为啥使用的newtonsoft.json版本限制为不大于12.0.2，与其他工具包的版本不兼容

### ISSUE THREAD

**Issue by qinqingping** [aliyun/aliyun-openapi-net-sdk#343]
dotnet 版本：asp.net core 3.0
平台： Windows
产品名称：sts

![image](https://user-images.githubusercontent.com/19235214/70123116-f216fc00-16ac-11ea-8097-764bc501e2a1.png)
![image](https://user-images.githubusercontent.com/19235214/70123168-0a871680-16ad-11ea-85fd-e828ee3c5092.png)

**Comment by AxiosCros** [comment]
感谢反馈，已更新 `aliyun-net-sdk-sts` 至 `3.0.4` 版本。
