### ISSUE TITLE
写这么“烂”的东西给鬼看？

### ISSUE THREAD

**Issue by TopGuo** [aliyun/aliyun-openapi-net-sdk#344]
对接人脸服务端，于是看了这篇文章
https://help.aliyun.com/document_detail/99222.html
![image](https://user-images.githubusercontent.com/30146744/70222246-b2234800-1784-11ea-944f-f58afafb812d.png)
别的语言都给了详细介绍 c#聊聊几笔 把我们引导到这里
![image](https://user-images.githubusercontent.com/30146744/70222330-dc750580-1784-11ea-88ff-03691aeb186a.png)
https://github.com/aliyun/aliyun-openapi-net-sdk/tree/master/aliyun-net-sdk-saf/Saf
看了这里这么烂的sdk 给鬼看？
![image](https://user-images.githubusercontent.com/30146744/70222436-0af2e080-1785-11ea-8e82-d173fec6ff51.png)
真不如的很失望！

**Comment by liaoyustudent** [comment]
你好，部分文档没有写明调用的 `demo` .可以通过 API Explore 来查看：

**Comment by TopGuo** [comment]
建议可以加个 example

**Comment by TopGuo** [comment]
### 本地调试 error
```
Error Message:
    Aliyun.Acs.Core.Exceptions.ClientException : SDK.InvalidRegionId : Can not find endpoint to access.
```
###  code

```
[Fact]
        public void TestAliYun()
        {
            //acess key secret=
            //access id=
            IClientProfile profile = DefaultProfile.GetProfile("cn-shanghai", "", "");
            DefaultAcsClient client = new DefaultAcsClient(profile);
            // var request = new ExecuteRequestRequest();
            ExecuteRequestRequest request = new ExecuteRequestRequest();
            request.AcceptFormat = FormatType.JSON;
            request.Service = "fin_face_verify";
            //发起认证
            request.ServiceParameters = new
            {
                method = "init",
                sceneId = "1000000025",
                outerOrderNo = "e0c34a77f5ac40a5aa5e6ed20c353888",
                bizCode = "FACE_SDK",
                identityType = "CERT_INFO",
                certType = "IDENTITY_CARD",
                certNo = "130726199512263114",
                certName = "郭东生",
                returnUrl = ""
            }.GetJson();
            var response = client.GetAcsResponse(request);
            var strContent = System.Text.Encoding.Default.GetString(response.HttpResponse.Content);
            
            Console.WriteLine(strContent);

            UnmarshallerContext context = strContent.GetModel<UnmarshallerContext>();//new UnmarshallerContext();
            var rep = request.GetResponse(context);
            System.Console.WriteLine("rep=>", rep);
        }

```
![image](https://user-images.githubusercontent.com/30146744/70242191-5d46f800-17ab-11ea-9434-906816c79167.png)

### 最后问题是
这个DefaultAcsClient 是不是不能在本地使用？

**Comment by TopGuo** [comment]
完整error code
```
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (64-bit .NET Core 4.6.27617.05)
[xUnit.net 00:00:00.79]   Discovering: test2
[xUnit.net 00:00:00.85]   Discovered:  test2
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (64-bit .NET Core 4.6.27617.05)
[xUnit.net 00:00:00.76]   Starting:    test2
[xUnit.net 00:00:00.92]     test2.UnitTest1.TestAliYun [FAIL]
[xUnit.net 00:00:00.92]       **Aliyun.Acs.Core.Exceptions.ClientException : SDK.InvalidRegionId : Can not find endpoint to access.**
[xUnit.net 00:00:00.92]       Stack Trace:
[xUnit.net 00:00:00.92]            at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, String regionId, Credential credential, ISigner signer, List`1 endpoints)
[xUnit.net 00:00:00.92]            at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, IClientProfile profile)
[xUnit.net 00:00:00.92]            at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request)
[xUnit.net 00:00:00.92]            at Aliyun.Acs.Core.DefaultAcsClient.GetAcsResponse[T](AcsRequest`1 request)
```

**Comment by JacksonTian** [comment]
麻烦您在运行测试的时候设置一下环境变量：DEBUG=sdk， 可以看到运行过程中的详细网络日志。参考： https://github.com/aliyun/aliyun-openapi-net-sdk/blob/master/docs/2-Debug-EN.md

**Comment by TopGuo** [comment]
设置环境变量 debug 后 依然是之前的错误
![image](https://user-images.githubusercontent.com/30146744/70285837-da9e5700-1803-11ea-803b-1d4906d5661b.png)

截图如下：
![image](https://user-images.githubusercontent.com/30146744/70285809-c0fd0f80-1803-11ea-85bc-5b1691de8282.png)

**Comment by TopGuo** [comment]
提供调用GetAcsResponce(request)时，request 入参的数据
![image](https://user-images.githubusercontent.com/30146744/70287335-7ed6cc80-1809-11ea-95bf-c92076e357ed.png)
{"ServiceParameters":"{\"method\":\"init\",\"sceneId\":\"1000000025\",\"outerOrderNo\":\"e0c34a77f5ac40a5aa5e6ed20c353888\",\"bizCode\":\"FACE_SDK\",\"identityType\":\"CERT_INFO\",\"certType\":\"IDENTITY_CARD\",\"certNo\":\"130726199512263114\",\"certName\":\"郭东生\",\"returnUrl\":\"\"}","Service":"fin_face_verify","ActionName":"ExecuteRequest","Version":"2018-09-19","AcceptFormat":1,"Product":"saf","Composer":{},"Protocol":1,"QueryParameters":{"Version":"2018-09-19","Action":"ExecuteRequest","Format":"JSON","Service":"fin_face_verify","ServiceParameters":"{\"method\":\"init\",\"sceneId\":\"1000000025\",\"outerOrderNo\":\"e0c34a77f5ac40a5aa5e6ed20c353888\",\"bizCode\":\"FACE_SDK\",\"identityType\":\"CERT_INFO\",\"certType\":\"IDENTITY_CARD\",\"certNo\":\"130726199512263114\",\"certName\":\"郭东生\",\"returnUrl\":\"\"}"},"Headers":{"x-sdk-client":"NetCore/4.6.2"},"Method":0}

**Comment by liaoyustudent** [comment]
您好，请问您现在引用的aliyun-net-sdk-core的版本是否是最新的1.5.3。目前我这边暂时没有重现您的问题。

**Comment by TopGuo** [comment]
谢谢 是的 坑死我了
我已经把引用改成了aliyun-net-sdk-core 1.5.3
调用成功 
![image](https://user-images.githubusercontent.com/30146744/70293778-599f8980-181c-11ea-81f9-6707ed5644b9.png)

**Comment by TopGuo** [comment]
你好 这个返回的内容为何好文档说明的内容不一致
程序返回
![image](https://user-images.githubusercontent.com/30146744/70297629-d8e78a00-1829-11ea-81ec-feb620a632f2.png)
文档说明
![image](https://user-images.githubusercontent.com/30146744/70297647-e9980000-1829-11ea-9cb5-4b8620c3a283.png)

**Comment by TopGuo** [comment]
开启debug 调用GetAcsResponse()时打印
![image](https://user-images.githubusercontent.com/30146744/70299034-aee49680-182e-11ea-92e4-bc0fa4ef30eb.png)
Message": "Specified signature nonce was used already."
signature 我并没有设置 是sdk里自动生成的吧

**Comment by liaoyustudent** [comment]
> 开启debug 调用GetAcsResponse()时打印
> ![image](https://user-images.githubusercontent.com/30146744/70299034-aee49680-182e-11ea-92e4-bc0fa4ef30eb.png)
> Message": "Specified signature nonce was used already."
> signature 我并没有设置 是sdk里自动生成的吧

你好，signature 是每次调用时sdk会帮你自动生成的验证签名，出现这个结果是否是因为您在调试时拖动过调试进度，反复调用了接口。

**Comment by liaoyustudent** [comment]
> 你好 这个返回的内容为何好文档说明的内容不一致
> 程序返回
> ![image](https://user-images.githubusercontent.com/30146744/70297629-d8e78a00-1829-11ea-81ec-feb620a632f2.png)
> 文档说明
> ![image](https://user-images.githubusercontent.com/30146744/70297647-e9980000-1829-11ea-9cb5-4b8620c3a283.png)

你好，我们这边负责根据产品的配置生成 sdk ，保证调用成功。如果发现文档和实际调用返回不一致，建议您向阿里云提一个工单，会有人员跟进您的问题。

**Comment by TopGuo** [comment]
![image](https://user-images.githubusercontent.com/30146744/70300260-02a4af00-1832-11ea-846b-a494c5bc1b86.png)
https://help.aliyun.com/document_detail/99222.html
这个文档中 签名机制指向的页面 显示内容升级中 
![image](https://user-images.githubusercontent.com/30146744/70300312-29fb7c00-1832-11ea-8117-7e3fe6044b49.png)
https://help.aliyun.com/document_detail/66384.html?spm=a2c4g.11186623.2.14.287721b9DFda8x
我准备用post 请求了不打算使用sdk了
请问你们这个的签名机制是什么？

**Comment by liaoyustudent** [comment]
> 我准备用post 请求了不打算使用sdk了
> 请问你们这个的签名机制是什么？

您好，建议您等文档更新完。或者直接查看我们core的开源的源码，在DoAction方法中会调用生成签名。源码地址：

**Comment by TopGuo** [comment]
好的
