### ISSUE TITLE
请问为什么要将aliyun-net-sdk-vod的Newtonsoft.Json包版本要求设置为小于等于12.0.2？

### ISSUE THREAD

**Issue by caopengfei** [aliyun/aliyun-openapi-net-sdk#345]

**Comment by caopengfei** [comment]
我看到有人提出sts也有同样的问题，你们已经修复了，但是vod却没有新版本，所以还请你们检查一下其他的项目是否也存在这样的问题，谢谢。

**Comment by AxiosCros** [comment]
感谢反馈。
sdk 是由生成器自动生成的，产品方通过发布系统申请发布 SDK。
生成器更新后，确实会出现部分产品未及时更新的情况。
以后我们会逐渐改进流程的。
