### ISSUE TITLE
aliyun-net-sdk-green的sdk版本依赖Newtonsoft.Json (<= 12.0.2)

### ISSUE THREAD

**Issue by ccccccmd** [aliyun/aliyun-openapi-net-sdk#347]
在dotnet core 2.2 升级到3.1得时候，版本不兼容

dotnet 版本：3.1
产品名称：green

![image](https://user-images.githubusercontent.com/10289019/70787124-0653ab00-1dc9-11ea-818d-99e872f55b91.png)

**Comment by liaoyustudent** [comment]
> 在dotnet core 2.2 升级到3.1得时候，版本不兼容
> 
> dotnet 版本：3.1
> 产品名称：green
> 
> ![image](https://user-images.githubusercontent.com/10289019/70787124-0653ab00-1dc9-11ea-818d-99e872f55b91.png)

您好，已发布 `aliyun-net-sdk-green 3.5.2`，解决 `Newtonsoft.Json` 约束问题。
