### ISSUE TITLE
视频点播SDK小建议

### ISSUE THREAD

**Issue by bill1411** [aliyun/aliyun-openapi-net-sdk#356]
视频点播提供了对视频截图的功能，在使用中发现一个小问题
当我提供的截图宽高参数超过视频本身的宽高参数时，系统默认用了视频宽高的参数截图。

是否可以在检测到这种情况后对超出的部分做黑色补图？

**Comment by liaoyustudent** [comment]
您好，感谢您为我们的产品提交建议。我们的 `sdk` 是对产品 `api` 请求的包装。产品本身的功能 `sdk` 是没办法修改的。建议您由阿里云官网提交一个功能建议，地址：
https://connect.aliyun.com/suggestion/add
