### ISSUE TITLE
需要vod uploader

### ISSUE THREAD

**Issue by tkezyo** [aliyun/aliyun-openapi-net-sdk#357]
如题

**Comment by liaoyustudent** [comment]
您好，感谢您为我们的产品提交建议。我们的 sdk 是对产品 api 请求的包装。产品本身的功能及sdk版本需求，建议您由阿里云官网提交一个功能建议，地址：
https://connect.aliyun.com/suggestion/add

**Comment by JacksonTian** [comment]
@tkezyo 我已经将你的需求转给相关的产品方了。
