### ISSUE TITLE
aliyun-net-sdk-live 对 Newtonsoft.Json 版本限制错误问题

### ISSUE THREAD

**Issue by hetaoos** [aliyun/aliyun-openapi-net-sdk#359]
[aliyun-net-sdk-live](https://www.nuget.org/packages/aliyun-net-sdk-live/) 对 Newtonsoft.Json 的引用要求版本 <= 12.0.2，这个有点不合理啊，是不是符号写反了？能否尽快修复下这个问题？

![Newtonsoft Json ](https://user-images.githubusercontent.com/1094462/78241478-0233d080-7513-11ea-87f0-3318ea810aae.png)

目前有些其他组件（比如 [DotNetCore.CAP](https://www.nuget.org/packages/DotNetCore.CAP/)）声明要求 >= 12.0.3，然后就无法编译了。

**Comment by hetaoos** [comment]
目前此类问题的包还有：

>aliyun-net-sdk-arms
aliyun-net-sdk-vpc
aliyun-net-sdk-ccc
aliyun-net-sdk-foas
aliyun-net-sdk-cusanalytic_sc_online
aliyun-net-sdk-cloudapi
aliyun-net-sdk-live
aliyun-net-sdk-companyreg
aliyun-net-sdk-ecsdemo
aliyun-net-sdk-market
aliyun-net-sdk-aliyuncvc
aliyun-net-sdk-iqa
aliyun-net-sdk-scdn

要不一次性解决完全？

**Comment by liaoyustudent** [comment]
感谢您的建议，目前有问题的sdk已全部重新发布。
