### ISSUE TITLE
阿里云短信服务的相关API没有SDK吗？

### ISSUE THREAD

**Issue by baiyunchen** [aliyun/aliyun-openapi-net-sdk#36]
请告知短信服务API的使用方法，谢谢！

**Comment by conan425** [comment]
@baiyunchen 您好，请您参考阿里云对应产品的官方api文档，如果没有查到SDK，可以通过客服或者提交工单的形式告诉我们，我们会有专门的同学去推动相关部门增加SDK，谢谢！
