### ISSUE TITLE
CommonRequest 增加链式操作

### ISSUE THREAD

**Issue by simhgd** [aliyun/aliyun-openapi-net-sdk#360]
**您的功能请求是否与问题有关？ 请描述一下。**

现有的CommonRequest 操作不便，希望增加链式操作，

> 当前
```csharp
var request = new CommonRequest {
 ...
};
request.AddQueryParameters(...);
request.AddQueryParameters(...);
request.AddQueryParameters(...);

```

> 希望
```csharp
var request = new CommonRequest {
 ...
}
.AddQueryParameters(...)
.AddQueryParameters(...)
.AddQueryParameters(...);
```

**描述你想要的解决方案**

Aliyun.Acs.Core.CommonRequest中相关方法返回值从void变成Aliyun.Acs.Core.CommonRequest

> [AddQueryParameters](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/da7587314c919d3eb28688e29d1c07d387b18fc6/aliyun-net-sdk-core/CommonRequest.cs#L150)

> [AddBodyParameters](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/da7587314c919d3eb28688e29d1c07d387b18fc6/aliyun-net-sdk-core/CommonRequest.cs#L155)

> [AddHeadParameters](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/da7587314c919d3eb28688e29d1c07d387b18fc6/aliyun-net-sdk-core/CommonRequest.cs#L160)

> [AddPathParameters](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/da7587314c919d3eb28688e29d1c07d387b18fc6/aliyun-net-sdk-core/CommonRequest.cs#L165)

**描述您考虑过的替代方案**

无

**Comment by liaoyustudent** [comment]
您好，感谢您的建议。我们会认真考虑您提供的解决方案，继续完善我们的sdk。
