### ISSUE TITLE
GetAcsResponse 无法获取 Response 直接退出程序

### ISSUE THREAD

**Issue by CoderLJY** [aliyun/aliyun-openapi-net-sdk#366]
* **Dotnet Core 版本**：netcoreapp3.1
* **平台**：win10
* **产品名称**：Aliyun.Acs.Dm
* **产品版本**：Aliyun.Acs.Dm.Model.V20151123
* **API**：GetAcsResponse

发送 SingleSendMailRequest 无法 get response ，直接退出程序。

**Comment by liaoyustudent** [comment]
你好，是否有具体的调用代码。

**Comment by liaoyustudent** [comment]
你好，这个问题我先关掉了。如果还出现问题，可以直接提工单附调用代码。我们会帮您解决
