### ISSUE TITLE
vodsdk域名指向错误

### ISSUE THREAD

**Issue by zhzhwcn** [aliyun/aliyun-openapi-net-sdk#367]
* **Dotnet Core 版本**：2.2
* **平台**：all
* **产品名称**：Vod
* **产品版本**：2.15.9
* **API**：CreateUploadVideo

[https://github.com/aliyun/aliyun-openapi-net-sdk/blob/master/aliyun-net-sdk-vod/Vod/Endpoint.cs#L43](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/master/aliyun-net-sdk-vod/Vod/Endpoint.cs#L43)
此处指定cn-shenzhen的endpoint为vod.cn-shanghai.aliyuncs.com
应该为vod.cn-shenzhen.aliyuncs.com

**Comment by liaoyustudent** [comment]
请问是否出现调用不通的问题？endpoint的规则是由产品方定义的，如果存在问题，可以在阿里云官网提一个工单反映这个问题。这边的问题我们先关掉了，感谢您的建议

**Comment by zhzhwcn** [comment]
调用是通的，但是直接使用以下方法指定服务区域的时候并不会将数据发送到`cn-shenzhen`

    IClientProfile profile = DefaultProfile.GetProfile(
        "cn-shenzhen",
        "<your-access-key-id>",
        "<your-access-key-secret>");
    DefaultAcsClient client = new DefaultAcsClient(profile);

因为sdk中的`cn-shenzhen`的域名还是`vod.cn-shanghai.aliyuncs.com`，所以数据还是发送到了`cn-shanghai`区域，需要调用

    var profile = DefaultProfile.GetProfile("cn-shenzhen", accessKeyId, accessKeySecret);
    profile.AddEndpoint("cn-shenzhen", "cn-shenzhen", "vod", "vod.cn-shenzhen.aliyuncs.com");

覆盖掉sdk中的配置才能将数据发到`cn-shenzhen`

**Comment by liaoyustudent** [comment]
嗯，我们的sdk是由产品方来给出业务规则生成的。如果这样是不合理的，建议您可以向产品方提个工单，以解决这个问题。
