### ISSUE TITLE
aliyun-net-sdk-core里的DefaultAcsClient在断网的请求连接时候会卡死

### ISSUE THREAD

**Issue by gitkeidy** [aliyun/aliyun-openapi-net-sdk#37]
aliyun-net-sdk-core里的DefaultAcsClient在断网的请求连接时候会卡死在GetAcsResponse这里。

BatchGetDeviceStateResponse response = client.GetAcsResponse(request);

**Comment by conan425** [comment]
@gitkeidy 您有具体的场景吗，我们看下能否复现，看看是SDK的问题还是具体接口的问题，您也可以加入我们的官方SDK钉钉群，群号是：11771185，谢谢

**Comment by doublnt** [comment]
您好，本地根据您提供的信息在断网时所复现出来的场景暂未出现卡死的状态，麻烦您使用最新版本的Nuget 包，再进行重试，如果您还遇到了问题，麻烦您提相应的Issue。
