### ISSUE TITLE
ECI not supported?

### ISSUE THREAD

**Issue by undefinedfunction** [aliyun/aliyun-openapi-net-sdk#374]
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

SDK doesn't seem to support ECI

**Describe the solution you'd like**
ECI Support in SDK

**Describe alternatives you've considered**
I see ECI support in Python/Java SDK but not .net, is this correct? Any idea when support will be provided?

**Comment by JacksonTian** [comment]
Hi @undefinedfunction Please use  https://github.com/aliyun/alibabacloud-sdk/tree/master/eci-20180808/csharp .

**Comment by undefinedfunction** [comment]
Thank you, I will check this out. I ended up achieving a result through serverless Kubernetes but this incurs extra cost so I will try this. 

Thanks again.
