### ISSUE TITLE
Aliyun.Acs.Alidns.Model Response 缺少调用错误的返回字段

### ISSUE THREAD

**Issue by simhgd** [aliyun/aliyun-openapi-net-sdk#379]
* **Dotnet Core 版本**：3.1.302
* **平台**：Windows
* **产品名称**：`Alidns`
* **产品版本**：`all`
* **API**：`all`

Alidns SDK中的所有response都没有处理调用错的的返回字段`Code`, `Message`,
导致调用后需要解析http response判断调用状态。以及提取错误码和错误信息。

REQUEST
```
https://alidns.aliyuncs.com/?AccessKeyId=<>&Action=DescribeSubDomainRecords&Format=JSON&RegionId=default&SecureTransport=true&SignatureMethod=HMAC-SHA1&SignatureNonce=983563768994953541f9fac09852ab19&SignatureVersion=1.0&SourceIp=<>&SubDomain=<>&Timestamp=2020-07-30T02%3A05%3A20Z&Version=2015-01-09&Signature=j%2Bh7ZxfJORJ8V%2B50VMixEd3oK44%3D
```

RESPONSE
```JSON
{
	"RequestId": "5291AE40-F25B-446C-A348-166B08989800",
	"HostId": "alidns.aliyuncs.com",
	"Code": "IncorrectDomainUser",
	"Message": "The domain name belongs to other users. Transfer the domain name to the current user and then try the binding and setting actions."
}
```

MODEL
[DescribeSubDomainRecordsResponse](https://github.com/aliyun/aliyun-openapi-net-sdk/blob/1d427ccd8ad365d5818a23df58f660a248b58db3/aliyun-net-sdk-alidns/Alidns/Model/V20150109/DescribeSubDomainRecordsResponse.cs#L25)

**Comment by liaoyustudent** [comment]
您好，SDK在请求返回错误码时应会抛出错误，不需要再对Response进行解析，是否有具体的示例截图
