### ISSUE TITLE
项目生成失败

### ISSUE THREAD

**Issue by talabrihgt** [aliyun/aliyun-openapi-net-sdk#38]
Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.	aliyun-net-sdk-core.vs2010
package文件没有

**Comment by iceagez** [comment]
遇到了同样的问题，解决了么？

**Comment by iceagez** [comment]
我找到解决办法了，原因是VS2017.3的一个bug，是由于2017和20102个解决方案公用同一个obj导致的。
解决方法：删除项目中的obj文件夹即可
