### ISSUE TITLE
Aliyun.Acs.Alidns.Model.V20150109.AddDomainRecordRequest 文档与SDK不符

### ISSUE THREAD

**Issue by simhgd** [aliyun/aliyun-openapi-net-sdk#380]
* **Dotnet Core Version**: 3.1.302
* **Platform**: Windows
* **Product**: Alidns
* **Product Version**: V20150109
* **API**: AddDomainRecordRequest
文档中请求参数名称 Value SDK中属性名为 _Value

文档地址
>  https://help.aliyun.com/document_detail/29772.html?spm=a2c4g.11186623.6.664.24fb2846RJjFEG

MODEL
> https://github.com/aliyun/aliyun-openapi-net-sdk/blob/1d427ccd8ad365d5818a23df58f660a248b58db3/aliyun-net-sdk-alidns/Alidns/Model/V20150109/AddDomainRecordRequest.cs#L112

**Comment by liaoyustudent** [comment]
您好，生成SDK时由于一些特殊或者重复的参数名，会在参数名前加下划线 `_` ，这是SDK的生成规则，最终向服务器发送请求时，参数名会转换成Value。
