### ISSUE TITLE
引用NuGet上的aliyun-net-sdk-dm-net包时提示与项目不完全兼容

### ISSUE THREAD

**Issue by Sunhelter** [aliyun/aliyun-openapi-net-sdk#381]
请问能否更新至dotnet Core版？

* **Dotnet Core Version**: 3.1
* **Platform**: Windows 10 Pro (64-bit) Version 2004
* **Product**: aliyun-net-sdk-dm
* **Product Version**: 1.0.0

**Comment by liaoyustudent** [comment]
您好，目前 Nuget 上 Dm 的SDK 包名被私人占用了，暂时没有正式的官方版本，后续会申诉将包名取回。其他的产品SDK是支持 dotnet core 的
