### ISSUE TITLE
没有实时语音识别的吗

### ISSUE THREAD

**Issue by wwping** [aliyun/aliyun-openapi-net-sdk#385]
**您的功能请求是否与问题有关？ 请描述一下。**
没有实时语音识别的吗，只能语音交互里面的实时语音识别  websoket的，文档又写的很晦涩难懂

**Comment by liaoyustudent** [comment]
您好，我们的SDK是由产品方来定义及生成。如未找到对应的SDK ，可以在阿里云官网提交建议。

**Comment by wwping** [comment]
好的吧，谢谢
