### ISSUE TITLE
aliyun-net-sdk-core  1.1.12 版本导致SDK.InvalidRegionId

### ISSUE THREAD

**Issue by johnnyqian** [aliyun/aliyun-openapi-net-sdk#40]
最新代码中的 endpoints.xml 导致 iot 调用服务时发生SDK.InvalidRegionId 错误。

回退到 1.1.8 版后，问题解决。

原因是 endpoints.xml 中对 iot 服务地址的定义没有了，regional_endpoint_pattern 也没有发挥作用：
```xml
  <product> 
    <code>iot</code>  
    <location_service_code>iot</location_service_code>  
    <document_id>30557</document_id>  
    <regional_endpoints></regional_endpoints>  
    <global_endpoint/>  
    <regional_endpoint_pattern>iot.[RegionId].aliyuncs.com</regional_endpoint_pattern> 
  </product>  
```

**Comment by AxiosCros** [comment]
@johnnyqian 
不是核心库的问题，是iot请求类的代码在生成时少了两个参数，已通知iot产品部门重新生成sdk了。

**Comment by lhg0302** [comment]
这个问题解决了没有,我今天下载最新版本,还是出现这个错误啊

**Comment by AxiosCros** [comment]
@lhg0302  已经解决了，一直在催iot产品部门发版本，应该很快就能发了。

**Comment by AxiosCros** [comment]
已更新，请使用iot 6.6.2版本。

**Comment by lhg0302** [comment]
<product> 
    <code>iot</code>  
    <location_service_code>iot</location_service_code>  
    <document_id>30557</document_id>  
    <regional_endpoints></regional_endpoints>  
    <global_endpoint/>  
    <regional_endpoint_pattern>iot.[RegionId].aliyuncs.com</regional_endpoint_pattern> 
  </product>
是由aliyun-net-sdk-core这个生成的,现在sdk-core没有更新,刚刚试过了,还是一样的问题

**Comment by AxiosCros** [comment]
@lhg0302 

找到问题原因了，iot产品不支持cn-hangzhou这个regionId，所以接口报InvalidRegionId是没问题的。

iot产品支持的regionId有以下几个：

cn-shanghai 上海
ap-southeast-1 新加坡
ap-northeast-1 日本东京
eu-central-1 德国法兰克福
us-west-1 美国硅谷
us-east-1 美国弗吉尼亚
