### ISSUE TITLE
本项目与alibabacloud-csharp-sdk应如何选择？

### ISSUE THREAD

**Issue by SimTsai** [aliyun/aliyun-openapi-net-sdk#405]
本项目和[alibabacloud-csharp-sdk](https://github.com/aliyun/alibabacloud-csharp-sdk)应该如何选择

**Comment by yndu13** [comment]
推荐[alibabacloud-csharp-sdk](https://github.com/aliyun/alibabacloud-csharp-sdk)，也就是 V2.0 版的 SDK。

**Comment by SimTsai** [comment]
> 推荐[alibabacloud-csharp-sdk](https://github.com/aliyun/alibabacloud-csharp-sdk)，也就是 V2.0 版的 SDK。

了解了,谢谢.
