### ISSUE TITLE
.net 平台更新很快。建议阿里的相关的sdk，随着.net 更新，也要更新下

### ISSUE THREAD

**Issue by HuaFangYun** [aliyun/aliyun-openapi-net-sdk#406]
.net 平台更新很快。建议阿里的相关的sdk，随着.net 更新，也要更新下

**Comment by yndu13** [comment]
推荐 V2.0 SDK，[alibabacloud-csharp-sdk](https://github.com/aliyun/alibabacloud-csharp-sdk)。使用文档参考https://help.aliyun.com/document_detail/378669.html

**Comment by HuaFangYun** [comment]
收到。谢谢！建议要保持更新。这样开发者才会觉得我们重视。更好使用我们的产品。据我了解很多.net开发都觉得阿里的.net sdk很烂。我觉得还是需要我们更的跟进，把遇到的问题及时处理和沟通。解决问题。
