### ISSUE TITLE
这块有没有计划提供.net framework版本的sdk啊

### ISSUE THREAD

**Issue by yh371174229** [aliyun/aliyun-openapi-net-sdk#42]
这块有没有计划提供.net framework版本的sdk啊

**Comment by xiaoyuvax** [comment]
自己把代码拷贝到.net framework的工程里面编译就可以了。

**Comment by gaoconggit** [comment]
有编译好的dll么？

**Comment by gaoconggit** [comment]
https://github.com/aliyun/aliyun-openapi-net-sdk/tree/ed0798071204a39acb93361f71ed0583278571b1/aliyun-net-sdk-sts/Sts/Model/V20150401

**Comment by gaoconggit** [comment]
@yh371174229

**Comment by yh371174229** [comment]
你就按照楼上手的，自己放到.net framework的工程里，编译一下就可以了哈
