### ISSUE TITLE
为什么 aliyun-net-sdk-alidns 没有发布到NuGet ？

### ISSUE THREAD

**Issue by rigious** [aliyun/aliyun-openapi-net-sdk#44]
在VS NuGet中能找到其他官方发布的依赖库，但是为什么没有 aliyun-net-sdk-alidns？

**Comment by sanjusss** [comment]
都9102年了，还没有发布……

**Comment by AxiosCros** [comment]
@sanjusss

**Comment by AxiosCros** [comment]
https://www.nuget.org/packages/aliyun-net-sdk-alidns/
