### ISSUE TITLE
ParameterHelper 中的 Md5Sum 实现不对

### ISSUE THREAD

**Issue by noliar** [aliyun/aliyun-openapi-net-sdk#5]
按照规范， `Content-MD5` 的计算结果应该用的是 Base64 编码，而 [`Md5Sum`](https://github.com/aliyun/aliyun-openapi-net-sdk/tree/master/aliyun-net-sdk-core/Utils/ParameterHelper.cs#L44-49)返回的是 Hex 编码的。（PS：看了下其他的 sdk 用的是 Base64）

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
