### ISSUE TITLE
aliyun-net-sdk-core获取语音识别token失败

### ISSUE THREAD

**Issue by liuhanwei1987** [aliyun/aliyun-openapi-net-sdk#54]
使用aliyun-net-sdk-core获取语音识别token失败，代码如下：
`public static string GetToken()
        {
            IClientProfile profile = DefaultProfile.GetProfile(region_id, ak_id, ak_secret);
            DefaultAcsClient client = new DefaultAcsClient(profile);
            CommonRequest request = new CommonRequest();
            request.Domain = "nls-meta.cn-shanghai.aliyuncs.com";
            request.Version = "2018-05-18";
            request.UriPattern = "/pop/2018-05-18/tokens";
            request.Method = Aliyun.Acs.Core.Http.MethodType.POST;

            CommonResponse response = client.GetCommonResponse(request);
            String result = response.Data;
            return result;
        }`
http返回状态200,返回数据:{}  (空的json)
同样的参数通过python sdk返回正常数据

**Comment by AxiosCros** [comment]
问题没有复现出来，可能已解决。
