### ISSUE TITLE
aliyun-net-sdk-dysmsapi 项目去哪里了？？

### ISSUE THREAD

**Issue by coolincy** [aliyun/aliyun-openapi-net-sdk#56]
之前从git拉取的代码有这个目录，最近更新发现没了，整个git历史记录里也没有了，你们用 force 强行删了代码么？

**Comment by WuMortal** [comment]
[https://help.aliyun.com/document_detail/55359.html?spm=a2c4g.11186623.2.16.4ca863caV5JTFH](https://help.aliyun.com/document_detail/55359.html?spm=a2c4g.11186623.2.16.4ca863caV5JTFH)

> 1、sdk工具包在解压后可以找到 aliyun-net-sdk-core.dll 和 aliyun-net-sdk-dysmsapi.dll 这两个文件。（ `net3.5`和`net2.0`的用户请使用`/api_demo/net2.0`目录下的；`core2.0`的用户请使用、`api_demo/core2.0/`目录下的）

**Comment by AxiosCros** [comment]
@coolincy 

dysms .net sdk 是直接在nuget平台上发布的
https://www.nuget.org/packages/aliyun-net-sdk-dysms/

``` shell
dotnet add package aliyun-net-sdk-dysms --version 1.0.6.2
```

**Comment by Nokecy** [comment]
![image](https://user-images.githubusercontent.com/12318131/56883203-8cb8b800-6a98-11e9-9085-a84ff4f107e7.png)
怎么弃用了呢 @AxiosCros

**Comment by doublnt** [comment]
@Nokecy  您可以参考 OpenApi Explorer上的使用示例来使用，https://api.aliyun.com/new?spm=a2c4g.11186623.2.13.3ae219d91ckRap#/?product=Dysmsapi&api=SendSms&params={}&tab=DEMO&lang=CSHARP

**Comment by AxiosCros** [comment]
@Nokecy 

产品方后续不再维护这个SDK了。
以后 dysms 产品都是使用 CommonRequest 配置相应参数进行接口请求。
