### ISSUE TITLE
.Net Framework版本太高了

### ISSUE THREAD

**Issue by swqsldz** [aliyun/aliyun-openapi-net-sdk#7]
.Net Framework 4.5的版本要求太高了。

**Comment by swqsldz** [comment]
希望能开一个低版本.Net Framework要求的branch

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
