### ISSUE TITLE
cdn sdk内文件缺失

### ISSUE THREAD

**Issue by swqsldz** [aliyun/aliyun-openapi-net-sdk#8]
cdn sdk内缺失IsGreyUserRequest.cs/IsGreyUserResponse.cs/IsGreyUserResponseUnmarshaller.cs

**Comment by ElaineFei** [comment]
您好，很抱歉当时没能及时回复您的问题，后续阿里云官方技术人员将为您提供高效的支持。若您仍有问题未能得到解答，请您重新提交issue。感谢您关注阿里云，关注阿里云 SDK。
