### ISSUE TITLE
这是我见过最差的SDK

### ISSUE THREAD

**Issue by coolyuwk** [aliyun/aliyun-openapi-net-sdk#9]
真不敢相信那么多代码一个字的注释都没有

**Comment by VAllens** [comment]
不是没有注释，而是把Help放在官网上了。
比如C#版本的Help在https://develop.aliyun.com/sdk/csharp
而API手册，访问https://develop.aliyun.com/sdk/csharp后，点击如下导航：SDK使用-->查看 API-->xxxxx。
比如域名解析，那么就是SDK使用-->查看 API-->云解析。

**Comment by fengyeju** [comment]
+1

**Comment by conan425** [comment]
谢谢大家的回复和建议 @VAllens @coolyuwk ，我们后续会继续完善。
